apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: create-katib-experiment
  namespace: admin
rules:
- apiGroups: ["kubeflow.org"]
  resources: ["experiments"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-katib-experiment-binding
  namespace: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-katib-experiment
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: admin
- kind: ServiceAccount
  name: default
  namespace: admin  
